---
version: "3.0"
services:
  wg-server:
    build: "./wg-server"
    image: wg-server:latest
    container_name: wg-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    command: /run.sh
    restart: unless-stopped
    networks:
      - docker-int-net

  torrent-server:
    build: "./torrent-server"
    image: torrent-server:latest
    container_name: torrent-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - $PWD/torrent-server/config/transmission:/etc/transmission-daemon
      - $PWD/torrent-server/downloads:/transmission/downloads
      - $PWD/torrent-server/incomplete:/transmission/incomplete
      - $PWD/torrent-server/torrents:/transmission/torrents
    ports:
      - 5234:5234/udp
    environment:
      - USERNAME="admin"
      - PASSWORD="password"
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    command: /run.sh
    restart: unless-stopped
    networks:
      - docker-int-net

networks:
  docker-int-net:
    name: docker-int-net
    driver: bridge
